### ISSUE TITLE
EbbRT front-end as shared object libraries

### ISSUE THREAD

**Issue by jmcadden** [SESA/EbbRT#100]
EbbRT's "front-end" runtime, or perhaps _EbbRT-on-Linux_, should be exist as a set of shared object libraries and headers installed onto the host operating system. This way an application can link in the EbbRT libraries and interact through interfaces defined in the EbbRT headers.  In general, we should strive to follow the "Linux way" of shared library organization, naming, placement, versioning and compatibility. 

I image EbbRT built as a collection of object libraries, wherein each library encapsulates one-or-more Ebbs which in turn depend a lower-level _runtime_ library. Application-specific objects can be built as static libraries and decoupled from the host installation. 

When we implement this approach it will bring to the forefront interesting issues about how EbbRT libraries should be written and how code can be shared between hosted and native implementations.

Thoughts? 

This enhancement would address issue #94

**Comment by jmcadden** [comment]
## Target Outline 

- [ ] Step 1. cmake install hosted EbbRT (shared/static) libraries onto system. 
- [ ] Step 2. New Hello World app & EbbRT-apps repo 
- [ ] Step 3. Install baremetal headers, build external baremetal libraries (cmake) 
- [ ] Step 4. Integrate EbbRT baremetal into toolchain to directly produce bootable img

**Comment by dschatzberg** [comment]
Closing this as complete with the latest toolchain
