### ISSUE TITLE
Backend 'quiet' print output

### ISSUE THREAD

**Issue by jimcadden** [SESA/EbbRT#96]
We need a simple way to quiet all debug print output when building back-end Release. I'm thinking a pre-processor define target within the app. We'll also need a way for the programmer to specify debug-only and required prints. For example: `#define __EBBRT_DEBUG_PRINT_ON__ 1`

**Comment by dschatzberg** [comment]
Here is my thoughts for how to do this. There should be a bunch of logging functions representing various levels of output (trace, debug, warn, info, error). And each of these functions should output based on the current log level (set by default to warn perhaps, but overridable by command line or FDT or environment variable.) This way we don't have to struggle too much for when to put debug output in the code, just choose the appropriate level

**Comment by jappavoo** [comment]
We went through several designs on this topic.  Questions about how to keep the checks flexible and 
yet potentially eliminate them all together to avoid overheads. (eg. no memory or coherency traffic).

I am happy to chat about the approaches we have looked at in the past.

**Comment by dschatzberg** [comment]
@jappavoo 
If possible, add thoughts to this post so we have it all documented. 

Another feature I would desire is the ability to enable/disable output per file, perhaps having the functions pass the value of the predefined FILE macro.

**Comment by jmcadden** [comment]
> logging functions representing various levels of output (trace, debug, warn, info, error)

Yes, I agree. We'd probably want both a "LogManager" Ebb, or a set of low-level kprintf-like functions (kprinf-debug(), kprintf-error(), kprintf-all()). 

> ability to enable/disable output per file, perhaps having the functions pass the value of the predefined FILE macro

I'm not sure I follow...a file-specific macro? E.g., `__EBBRT_EVENTMANAGER__QUIET_ALL__` ? 

> We went through several designs on this topic.

Here's a glance into one way we had previously hacked together a 'quiet' build: 
https://github.com/SESA/EbbRT/commit/546c1f9655ae81ccd4996d5cc9c5ff66560399d3

**Comment by dschatzberg** [comment]
@jmcadden 

> I'm not sure I follow...a file-specific macro? E.g., __EBBRT_EVENTMANAGER__QUIET_ALL__ ?

I'm motivated by the way Rust's `env_logger` works: https://rust-lang-nursery.github.io/log/env_logger/

GCC defines `__FILE__` to be the current file name. So if we had the (for example) `LOG()` macro pass the file name to the logging object. Then the logging object could decide to log (or not) based on some file-specific setting. For example, suppose we could configure the log output with some variable like so: `EBBRT_LOG="warn,EventManager=debug"` then all log output with `warn` or higher (e.g. `error`) will be output. However, any output in the `EventManager` with `debug` or higher will  be output.

**Comment by jmcadden** [comment]
For the time being: EbbRT baremetal has a [compilation flag that will mute kprintf() output](https://github.com/SESA/EbbRT/blob/master/baremetal/src/Debug.cc#L19
), along with a force_kprintf() that will print when others are muted.
