### ISSUE TITLE
System design review

### ISSUE THREAD

**Issue by jmcadden** [SESA/EbbRT#99]
Let's reserve a room for a couple of hours to review and discuss portions of the core EbbRT code up on the projector. This can be useful in getting (re)acquainted with the underlying components of EbbRT and the design decisions / implications which accompany them. 

Instead of having a single-presenter or a targeted region of code, I suggest this be held as a free-form discussion. For example, we begin with a high-level interface (e.g., `gp_allocator->Alloc(size)`) and follow whichever code+question path we decide is most interesting.

**Comment by dschatzberg** [comment]
Closing this as inappropriate for our issue tracker
